### ISSUE TITLE
Investigate CI failures related to scopelint

### ISSUE THREAD

**Issue by davidlaprade** [gitcoinco/Alpha-Governor-Upgrade#13]
In a recent PR, #5, all of the builds are failing because of scopelint formatting, for example [here](https://github.com/gitcoinco/2022-Governor-upgrade/actions/runs/3914906663/jobs/6692492151). Here's the error:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/7997618/212420528-40975a18-00f0-4b76-ae86-1436a2955cbe.png">

This is odd because scopelint passes locally:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/7997618/212420392-c814b95c-feca-4564-9ac4-dac2852d884d.png">

Notice, though, that CI seems to be on an older version than me -- 0.0.11 vs 0.0.12. [0.0.12](https://github.com/ScopeLift/scopelint/releases/tag/v0.0.12) is currently the [latest release](https://github.com/ScopeLift/scopelint/tags).

Looking at the CI configs in this repo, we've set the action up to install the latest release:

https://github.com/gitcoinco/2022-Governor-upgrade/blob/db5391726ec0eaec9bdabc998cdd5beba65d4967/.github/workflows/ci.yml#L69-L78

So I'm not sure what's going on here

**Comment by mds1** [comment]
You can see that v0.0.12 is actually the installed tag, and there's jut a bug in the `scopelint --version` command (I think I tried publishing before bumping the version number in the `cargo.toml` file IIRC).
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/17163988/212731327-42a2c6a4-9aac-44ed-9f3e-fcd28f9eec78.png">

Running `scopelint` locally for me results in formatting changes to `GitcoinGovernor.sol`, so I suspect you are not on the most recent foundry version where a default fmt parameter was changed: https://github.com/foundry-rs/foundry/pull/4023 (and since we don't specify this one in our foundry.toml, since it was added recently, but we should specify it, the forge change affects us here)

**Comment by davidlaprade** [comment]
> I suspect you are not on the most recent foundry version where a default fmt parameter was changed

Yup that was the issue. Sorry, closing this out
